Company.Web/Controllers/EmployeeController.cs
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web.Mvc;
using AutoMapper;
using Company.BLL.Abstract;
using Company.DTO.Concrete;
using Company.Web.Binders;
using Company.Web.Models;

namespace Company.Web.Controllers
{
     public class EmployeeController : Controller
     {
          private readonly IEmployeeService _service;
          private readonly IDepartmentService _serviceDepartment;

          public EmployeeController(IEmployeeService serviceEmployee, IDepartmentService departmentService)
          {
               _service = serviceEmployee;
               _serviceDepartment = departmentService;
          }

          [HttpGet]
          public ActionResult Index(int pageNumber = 1,
               int pageSize = 50,
               string sortOrder = "ascending",
               string sortBy = "LastName",
               string stringToFind = "",
               string category = "default")
          {
               var filter = new SortAndFilterDto
               {
                    SortOrder = sortOrder,
                    PageNumber = pageNumber,
                    PageSize = pageSize,
                    SortBy = sortBy,
                    StringToFind = stringToFind,
                    Category = category
               };

               var pagedEmployeeDto = _service.GetAll(filter);

               filter.TotalItems = pagedEmployeeDto.TotalItems;

               return View(new EmployeeListModel {PagedEmployees = pagedEmployeeDto, Filters = filter});
          }

          [HttpPost]
          public ActionResult Index(SortAndFilterDto filter)
          {
               var pagedEmployeesDto = _service.GetAll(filter);

               filter.TotalItems = pagedEmployeesDto.TotalItems;

               return View(new EmployeeListModel {PagedEmployees = pagedEmployeesDto, Filters = filter});
          }

          [HttpGet]
          public ActionResult Manage(int id, SortAndFilterDto filter)
          {
               var managedEmployee = (id == 0) ? new EmployeeDto() : _service.FindBy(id);

               var employeeModel = Mapper.Map<EmployeeDto, EmployeeModel>(managedEmployee);

               employeeModel.Filters = filter;

               if (managedEmployee != null)
               {
                    var departments = _serviceDepartment.GetAllDepartments()
                         .Select(d => new SelectListItem() {Value = d.Id.ToString(), Text = d.Name});
                    if (id != 0)
                    {
                         var selectedItem = departments.First(m => m.Value == managedEmployee.DepartmentId.ToString());
                         selectedItem.Selected = true;
                    }

                    ViewBag.Departments = departments;
                    return View("Modify", employeeModel);
               }
               else
               {
                    return View("Error", ViewBag.ErrorMessage = "Cannot find the Specified Employee");
               }
          }

          [HttpPost]
          public ActionResult Manage([ModelBinder(typeof(ManageEmployeeBinder))] EmployeeModel pagedEmployee)
          {
               ModelState.Clear();
               TryValidateModel(pagedEmployee);
               if (ModelState.IsValid)
               {
                    try
                    {
                         if (_service.IsUniqueField(pagedEmployee.Email, pagedEmployee.Id))
                         {
                              var employeeDto = Mapper.Map<EmployeeModel, EmployeeDto>(pagedEmployee);

                              _service.Manage(employeeDto);

                              return RedirectToAction("Index",
                                   new
                                   {
                                        pageNumber = 1,
                                        pageSize = pagedEmployee.Filters.PageSize,
                                        sortOrder = pagedEmployee.Filters.SortOrder,
                                        sortBy = pagedEmployee.Filters.SortBy,
                                        stringToFind = pagedEmployee.Filters.StringToFind,
                                        category = pagedEmployee.Filters.Category
                                   });
                         }
                         else
                         {
                              ModelState.AddModelError("", "Указанная почта уже занята! ");

                              var departments = _serviceDepartment.GetAllDepartments()
                                   .Select(d => new SelectListItem() {Value = d.Id.ToString(), Text = d.Name});
                              if (pagedEmployee.Id != 0)
                              {
                                   var selectedItem = departments.First(m =>
                                        m.Value == pagedEmployee.DepartmentId.ToString());
                                   selectedItem.Selected = true;
                              }

                              ViewBag.Departments = departments;
                              return View("Modify", pagedEmployee);
                         }
                    }
                    catch (DataException)
                    {
                         ModelState.AddModelError("", "Some problems with Database. Contact your Admin!");
                         return RedirectToAction("Index",
                              new
                              {
                                   pageNumber = 1,
                                   pageSize = pagedEmployee.Filters.PageSize,
                                   sortOrder = pagedEmployee.Filters.SortOrder,
                                   sortBy = pagedEmployee.Filters.SortBy,
                                   stringToFind = pagedEmployee.Filters.StringToFind,
                                   category = pagedEmployee.Filters.Category
                              });
                    }
               }
               else
               {
                    ModelState.AddModelError("", "Unable to save changes because of model validation failure! ");

                    var departments = _serviceDepartment.GetAllDepartments()
                         .Select(d => new SelectListItem() {Value = d.Id.ToString(), Text = d.Name});

                    var selectedItem = departments.First(m => m.Value == pagedEmployee.DepartmentId.ToString());
                    selectedItem.Selected = true;

                    ViewBag.Departments = departments;
                    return View("Modify", pagedEmployee);
               }
          }

          [HttpGet]
          public ActionResult Delete(int id, SortAndFilterDto filters)
          {
               try
               {
                    _service.Delete(id);

                    return RedirectToAction("Index",
                         new
                         {
                              pageNumber = 1,
                              pageSize = filters.PageSize,
                              sortOrder = filters.SortOrder,
                              sortBy = filters.SortBy,
                              stringToFind = filters.StringToFind,
                              category = filters.Category
                         });
               }
               catch
               {
                    return View("Error", ViewBag.ErrorMessage = "Some problems with Database. Contact your Admin!");
               }
          }
     }
}

Company.Web/Views/Employee/Index.cshtml
@using Company.DTO.Concrete
@using Company.Web.Helpers
@model Company.Web.Models.EmployeeListModel

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>List of Employees</h1>
@Html.ValidationSummary(false, "")
@using (Html.BeginForm("Index", "Employee", FormMethod.Post))
{
     <div class="aboveTableMenu">
          <a class="addbutton" href="@Url.Action("Manage", new {Id = 0,
                                          PageNumber = 1,
                                          Model.Filters.PageSize,
                                          Model.Filters.SortOrder,
                                          Model.Filters.SortBy,
                                          Model.Filters.Category,
                                          Model.Filters.StringToFind
                                     })">Add</a>
          <div class="dropdownMenu">
               @Html.Label("Искать в категории")
               @Html.DropDownList("Category", new List<SelectListItem>
               {
                    new SelectListItem {Text = "Выберите категорию", Value = "default", Selected = (Model.Filters.Category == "default")},
                    new SelectListItem {Text = "Имя", Value = "FirstName", Selected = (Model.Filters.Category == "FirstName")},
                    new SelectListItem {Text = "Фамилия", Value = "LastName", Selected = (Model.Filters.Category == "LastName")},
                    new SelectListItem {Text = "Гражданство", Value = "Citizenship", Selected = (Model.Filters.Category == "Citizenship")},
                    new SelectListItem {Text = "Опыту", Value = "Experience", Selected = (Model.Filters.Category == "Experience")},
                    new SelectListItem {Text = "Почте", Value = "Email", Selected = (Model.Filters.Category == "Email")},
                    new SelectListItem {Text = "Департамент", Value = "DepartmentName", Selected = (Model.Filters.Category == "DepartmentName")},

               }, new {@class = "dropdown"})<br />

               @Html.Label("Найти")
               @Html.TextBox("StringToFind", @Model.Filters.StringToFind, new { @class = "userInput" })

          </div>
          <div class="dropdownMenu">
               @Html.Label("Сортировать по")<br/>
               @Html.DropDownList("SortBy", new List<SelectListItem>
               {
                    new SelectListItem {Text = "ФИО", Value = "LastName", Selected = (Model.Filters.SortBy == "LastName")},
                    new SelectListItem {Text = "Дате рождения", Value = "DOB", Selected = (Model.Filters.SortBy == "DOB")},
                    new SelectListItem {Text = "Гражданству", Value = "Citizenship", Selected = (Model.Filters.SortBy == "Citizenship")},
                    new SelectListItem {Text = "Опыту", Value = "Experience", Selected = (Model.Filters.SortBy == "Experience")},
                    new SelectListItem {Text = "Почте", Value = "Email", Selected = (Model.Filters.SortBy == "Email")}
               }, new {@class = "dropdown"})
          </div>
          <div class="dropdownMenu">
               @Html.Label("В порядке")<br/>
               @Html.DropDownList("SortOrder", new List<SelectListItem>
               {
                    new SelectListItem {Text = "По возрастанию", Value = "ascending", Selected = Model.Filters.SortOrder == "ascending"},
                    new SelectListItem {Text = "По убыванию", Value = "descending", Selected = Model.Filters.SortOrder == "descending"}
               }, new {@class = "dropdown"})

          </div>
          <div class="dropdownMenu">
               @Html.Label("Количество")<br/>
               @Html.DropDownList("PageSize",
                    Enumerable.Range(50, 200).Where(i => i % 50 == 0).Select(i => new SelectListItem {Text = i.ToString(), Value = i.ToString(), Selected = Model.Filters.PageSize / i == 1}),
                    new {@class = "dropdown"})
          </div>

          <input type="hidden" name="PageNumber" value="@Model.Filters.PageNumber"/>
          <input class="submitBtn" type="submit" value="Отправить"/>
     </div>
}

<table class="listItems">
     <thead>
     <tr>
          <td></td>
          <td>FirstName LastName</td>
          <td>DOB</td>
          <td>Citizenship</td>
          <td>Experience</td>
          <td>Email</td>
          <td>Department</td>
          <td>Actions</td>
     </tr>
     </thead>
     <tbody>

     @foreach (var str in Model.PagedEmployees.List)
     {
          <tr>
               <td>@Html.Hidden("EmployeeId", str.Id)</td>
               <td>@str.LastName  @str.FirstName </td>
               <td>@str.DoB</td>
               <td>@str.Citizenship</td>
               <td>@str.Experience</td>
               <td>@str.Email</td>
               <td>@str.DepartmentName</td>
               <td>
                    <div class="crudButtons">

                         <a href="@Url.Action("Manage", new  {id = str.Id, PageNumber = 1,
                                       Model.Filters.PageSize,
                                       Model.Filters.SortOrder,
                                       Model.Filters.SortBy,
                                       Model.Filters.Category,
                                       Model.Filters.StringToFind
                                  })">Edit</a>
                         <a href="@Url.Action("Delete", new  {id = str.Id, PageNumber = 1,
                                       Model.Filters.PageSize,
                                       Model.Filters.SortOrder,
                                       Model.Filters.SortBy,
                                       Model.Filters.Category,
                                       Model.Filters.StringToFind})">Delete</a>

                    </div>
               </td>
          </tr>
     }
     </tbody>
</table>
s
<div class="pagination">
     @Html.PageLinks(Model.Filters.TotalPages,
          Model.Filters.PageNumber,
          x => Url.Action("Index", new
          {
               PageNumber = x,
               pageSize = Model.Filters.PageSize,
               sortOrder = Model.Filters.SortOrder,
               sortBy = Model.Filters.SortBy,
               Model.Filters.Category,
               stringToFind = Model.Filters.StringToFind
          }))
</div>

Company.Web/Views/Employee/Modify.cshtml
@model Company.Web.Models.EmployeeModel

@{
    ViewBag.Title = "Employee";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Employee</h2>
<form method="post">
     @Html.ValidationSummary(false, "")
     <input type="hidden" name="EmployeeId" value="@Model.Id" />
     <div class="formElement">
          <label>First name:</label>
          <input type="text" name="FirstName" value="@Model.FirstName">
          @Html.ValidationMessageFor(m => m.FirstName)
     </div>
     <div class="formElement">
          <label>Last name:</label>
          <input type="text" name="LastName" value="@Model.LastName" />
          @Html.ValidationMessageFor(m => m.LastName)
     </div>
     <div class="formElement">
          <label>Date of birth:</label>
          <input type="datetime" name="DoB" value="@Model.DoB" />
          @Html.ValidationMessageFor(m => m.DoB)
     </div>
     <div class="formElement">
          <label>Citizenship:</label>
          <input type="text" name="Citizenship" value="@Model.Citizenship" />
          @Html.ValidationMessageFor(m => m.Citizenship)
     </div>
     <div class="formElement">
          <label>Experience:</label>
          <input type="number" name="Experience" value="@Model.Experience" />
          @Html.ValidationMessageFor(m => m.Experience)
     </div>
     <div class="formElement">
          <label>Email:</label>
          <input type="email" name="Email" value="@Model.Email" />
          @Html.ValidationMessageFor(m => m.Email)
     </div>
     <div class="formElement">
          <label>Department:</label>
          @Html.DropDownList("DepartmentId", (IEnumerable<SelectListItem>)ViewBag.Departments)
     </div>

     <input type="hidden" name="PageSize" value="@Model.Filters.PageSize" />
     <input type="hidden" name="SortBy" value="@Model.Filters.SortBy" />
     <input type="hidden" name="SortOrder" value="@Model.Filters.SortOrder" />
     <input type="hidden" name="Category" value="default" />
     <input type="hidden" name="StringToFind" value="" />

     <input type="submit" name="OK" />
</form>