Company.Web/Controllers/DepartmentController.cs
using System.Web.Mvc;
using System.Data;
using AutoMapper;
using Company.BLL.Abstract;
using Company.DTO.Concrete;
using Company.Web.Models;
using Company.Web.Binders;

namespace Company.Web.Controllers
{
     public class DepartmentController : Controller
     {
          private readonly IDepartmentService _service;

          public DepartmentController(IDepartmentService service)
          {
               _service = service;
          }

          [HttpGet]
          public ActionResult Index(
               int pageNumber = 1, 
               int pageSize = 5, 
               string sortOrder = "ascending",
               string sortBy = "Name", 
               string stringToFind = "", 
               string category = "default")
          {
               var filter = new SortAndFilterDto
               {
                    SortOrder = sortOrder,
                    PageNumber = pageNumber,
                    PageSize = pageSize,
                    SortBy = sortBy,
                    Category = category,
                    StringToFind = stringToFind
               };

               var pagedDepartmentsDto = _service.GetAll(filter);

               filter.TotalItems = pagedDepartmentsDto.TotalItems;

               return View(new DepartmentListModel {PagedDepartments = pagedDepartmentsDto, Filters = filter});
          }

          [HttpPost]
          public ActionResult Index(SortAndFilterDto filter)
          {
               var pagedDepartmentsDto = _service.GetAll(filter);

               filter.TotalItems = pagedDepartmentsDto.TotalItems;

               return View(new DepartmentListModel {PagedDepartments = pagedDepartmentsDto, Filters = filter});
          }

          [HttpGet]
          public ActionResult Manage(int id, SortAndFilterDto filter)
          {
               var managedDepartment = (id == 0) ? new DepartmentDto() : _service.FindBy(id);

               // While Mapping Employees becomes equal to "null"
               var departmentModel = Mapper.Map<DepartmentDto, DepartmentModel>(managedDepartment);

               departmentModel.Filters = filter;

               return managedDepartment != null
                    ? View("Modify", departmentModel)
                    : (ActionResult) View("Error", ViewBag.ErrorMessage = "Cannot find the Specified Department");
          }

          [HttpPost]
          public ActionResult Manage([ModelBinder(typeof(ManageDepratmentBinder))] DepartmentModel pagedDepartment)
          {
               ModelState.Clear();
               TryValidateModel(pagedDepartment);
               if (ModelState.IsValid)
               {
                    try
                    {
                         if (_service.IsUniqueField(pagedDepartment.Name, pagedDepartment.Id))
                         {
                              var departmentDto = Mapper.Map<DepartmentModel, DepartmentDto>(pagedDepartment);

                              _service.Manage(departmentDto);

                              return RedirectToAction("Index",
                                   new
                                   {
                                        pageNumber = 1,
                                        pageSize = pagedDepartment.Filters.PageSize,
                                        sortOrder = pagedDepartment.Filters.SortOrder,
                                        sortBy = pagedDepartment.Filters.SortBy,
                                        stringToFind = pagedDepartment.Filters.StringToFind,
                                        category = pagedDepartment.Filters.Category
                                   });
                         }
                         
                         ModelState.AddModelError("Name", @"The name you are trying to enter is already taken!");

                         return View("Modify", pagedDepartment);
                         
                    }
                    catch (DataException)
                    {
                         ModelState.AddModelError("", @"Some problems with Database. Contact your Admin!");

                         return RedirectToAction("Index",
                              new
                              {
                                   pageNumber = 1,
                                   pageSize = pagedDepartment.Filters.PageSize,
                                   sortOrder = pagedDepartment.Filters.SortOrder,
                                   sortBy = pagedDepartment.Filters.SortBy,
                                   stringToFind = pagedDepartment.Filters.StringToFind,
                                   category = pagedDepartment.Filters.Category
                              });
                    }
               }
               else
               {
                    return View("Modify", pagedDepartment);
               }
          }

          public ActionResult Delete(int id, SortAndFilterDto filters)
          {
               try
               {
                    _service.Delete(id);
                    return RedirectToAction("Index",
                         new
                         {
                              pageNumber = 1,
                              pageSize = filters.PageSize,
                              sortOrder = filters.SortOrder,
                              sortBy = filters.SortBy,
                              stringToFind = filters.StringToFind,
                              category = filters.Category

                         });
               }
               catch (DataException)
               {
                    return View("Error", ViewBag.ErrorMessage = "Some problems with Database. Contact your Admin!");
               }
          }
     }
}

Company.Web/Views/Department/Index.cshtml
@model Company.Web.Models.DepartmentListModel
@using System.Linq;
@using System.Web.Mvc.Html
@using Company.Web.Helpers;

@{
     ViewBag.Title = "Index";
     Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>List of Departments</h1>
@Html.ValidationSummary(false, "")
<p>@ViewBag.ErrorMessage</p>

@using (Html.BeginForm("Index", "Department", FormMethod.Post))
{
<div class="aboveTableMenu">
     <a class="addbutton" href="@Url.Action("Manage", new {
                                     Id = 0,
                                     PageNumber = 1,
                                     Model.Filters.PageSize,
                                     Model.Filters.SortOrder,
                                     Model.Filters.SortBy,
                                     Model.Filters.Category,
                                     Model.Filters.StringToFind
                                })">Add</a>

     <div class="dropdownMenu">
          @Html.Label("Искать в категории")
          @Html.DropDownList("Category", new List<SelectListItem>
          {
               new SelectListItem {Text = "Выберите категорию", Value = "default", Selected = (Model.Filters.Category == "default")},
               new SelectListItem {Text = "Имя", Value = "Name", Selected = (Model.Filters.Category == "Name")},
               new SelectListItem {Text = "Описание", Value = "Description", Selected = (Model.Filters.Category == "Description")},
               new SelectListItem {Text = "Бюджет", Value = "Budget", Selected = (Model.Filters.Category == "Budget")}
          }, new {@class = "dropdown"})<br />

          @Html.Label("Найти")
          @Html.TextBox("StringToFind", @Model.Filters.StringToFind, new { @class = "userInput" })
     </div>
     <div class="dropdownMenu">
          @Html.Label("Сортировать по")<br />
          @Html.DropDownList("SortBy", new List<SelectListItem>
          {
               new SelectListItem {Text = "Имени", Value = "Name", Selected = (Model.Filters.SortBy == "Name")},
               new SelectListItem {Text = "Описанию", Value = "Description", Selected = (Model.Filters.SortBy == "Description")},
               new SelectListItem {Text = "Бюджету", Value = "Budget", Selected = (Model.Filters.SortBy == "Budget")}
          }, new {@class = "dropdown"})
     </div>
     <div class="dropdownMenu">
          @Html.Label("В порядке")<br />
          @Html.DropDownList("SortOrder", new List<SelectListItem>
          {
               new SelectListItem {Text = "По возрастанию", Value = "ascending", Selected = Model.Filters.SortOrder == "ascending"},
               new SelectListItem {Text = "По убыванию", Value = "descending", Selected = Model.Filters.SortOrder == "descending"}
          }, new {@class = "dropdown"})

     </div>
     <div class="dropdownMenu">
          @Html.Label("Количество")<br />
          @Html.DropDownList("PageSize",
               Enumerable.Range(5, 50).Where(i => i % 5 == 0).Select(i => new SelectListItem {Text = i.ToString(), Value = i.ToString(), Selected = Model.Filters.PageSize / i == 1}),
               new {@class = "dropdown"})
     </div>

     <input type="hidden" name="PageNumber" value="@Model.Filters.PageNumber" />
     <input class="submitBtn" type="submit" value="Отправить" />
</div>
}
<table class="listItems">
     <thead>
          <tr>
               <td></td>
               <td>Название</td>
               <td>Описание</td>
               <td>Бюджет</td>
               <td>Сотрудники</td>
               <td>Actions</td>
          </tr>
     </thead>
     <tbody>

          @foreach (var str in Model.PagedDepartments.List)
          {
               <tr>
                    <td>@Html.Hidden("DepartmentId", str.Id)</td>
                    <td>@str.Name</td>
                    <td>@str.Description</td>
                    <td>@str.Budget</td>
                    <td>
                         @if (str.Employees != null)
                         {
                              foreach (var emp in str.Employees)
                              {
                                   <p>@emp.FirstName @emp.LastName</p>
                              }
                         }
                    </td>
                    <td>
                         <div class="crudButtons">

                              <a href="@Url.Action("Manage", new  {str.Id, PageNumber = 1,
                                            Model.Filters.PageSize,
                                            Model.Filters.SortOrder,
                                            Model.Filters.SortBy,
                                            Model.Filters.Category,
                                            Model.Filters.StringToFind
                                       })">Edit</a>
                              <a href="@Url.Action("Delete", new  {str.Id, PageNumber = 1,
                                            Model.Filters.PageSize,
                                            Model.Filters.SortOrder,
                                            Model.Filters.SortBy,
                                            Model.Filters.Category,
                                            Model.Filters.StringToFind})">Delete</a>
                         </div>
                    </td>
               </tr>
          }
     </tbody>
</table>

<div class="pagination">
     @Html.PageLinks(Model.Filters.TotalPages,
          Model.Filters.PageNumber,
          x => Url.Action("Index", new
          {
               PageNumber = x,
               pageSize = Model.Filters.PageSize,
               sortOrder = Model.Filters.SortOrder,
               sortBy = Model.Filters.SortBy,
               category = Model.Filters.Category,
               stringToFind = Model.Filters.StringToFind

          }))
</div>

Company.Web/Views/Department/Modify.cshtml
@model Company.Web.Models.DepartmentModel

@{
    ViewBag.Title = "Create new department";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Department</h2>
<form method="post">
     @Html.ValidationSummary(false, "")
     <div class="formElement">
          <label>Department name:</label>
          <input type="text" name="Name" value="@Model.Name" />
          @Html.ValidationMessageFor(m => m.Name)
     </div>
     <div>
          <label>Description (Brief information about the department)</label>
          <input type="text" name="Description" value="@Model.Description" />
     </div>
     <div>
          <label>Budget</label>
          <input type="number" name="Budget" value="@Model.Budget" />
          @Html.ValidationMessageFor(m => m.Budget)
     </div>
     <input type="hidden" name="Id" value="@Model.Id" />

     <input type="hidden" name="PageSize" value="@Model.Filters.PageSize" />
     <input type="hidden" name="SortBy" value="@Model.Filters.SortBy" />
     <input type="hidden" name="SortOrder" value="@Model.Filters.SortOrder" />
     <input type="hidden" name="Category" value="default" />
     <input type="hidden" name="StringToFind" value="" />
     <input type="submit" name="OK" />
</form>